// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const checkPatchExists = `-- name: CheckPatchExists :many
SELECT id, user_id, patchset_id, author_name, author_email, author_date, title, body, body_appendix, commit_sha, content_sha, raw_text, base_commit_sha, created_at FROM patches WHERE patchset_id = ? AND content_sha = ?
`

type CheckPatchExistsParams struct {
	PatchsetID int64  `db:"patchset_id"`
	ContentSha string `db:"content_sha"`
}

func (q *Queries) CheckPatchExists(ctx context.Context, arg CheckPatchExistsParams) ([]Patch, error) {
	rows, err := q.db.QueryContext(ctx, checkPatchExists, arg.PatchsetID, arg.ContentSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patch
	for rows.Next() {
		var i Patch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PatchsetID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorDate,
			&i.Title,
			&i.Body,
			&i.BodyAppendix,
			&i.CommitSha,
			&i.ContentSha,
			&i.RawText,
			&i.BaseCommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEventLog = `-- name: CreateEventLog :exec
INSERT INTO event_logs (user_id, repo_id, patch_request_id, patchset_id, event, data) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateEventLogParams struct {
	UserID         int64         `db:"user_id"`
	RepoID         sql.NullInt64 `db:"repo_id"`
	PatchRequestID sql.NullInt64 `db:"patch_request_id"`
	PatchsetID     sql.NullInt64 `db:"patchset_id"`
	Event          string        `db:"event"`
	Data           EventData     `db:"data"`
}

func (q *Queries) CreateEventLog(ctx context.Context, arg CreateEventLogParams) error {
	_, err := q.db.ExecContext(ctx, createEventLog,
		arg.UserID,
		arg.RepoID,
		arg.PatchRequestID,
		arg.PatchsetID,
		arg.Event,
		arg.Data,
	)
	return err
}

const createPatch = `-- name: CreatePatch :one
INSERT INTO patches (user_id, patchset_id, author_name, author_email, author_date, title, body, body_appendix, commit_sha, content_sha, base_commit_sha, raw_text) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type CreatePatchParams struct {
	UserID        int64          `db:"user_id"`
	PatchsetID    int64          `db:"patchset_id"`
	AuthorName    string         `db:"author_name"`
	AuthorEmail   string         `db:"author_email"`
	AuthorDate    time.Time      `db:"author_date"`
	Title         string         `db:"title"`
	Body          string         `db:"body"`
	BodyAppendix  string         `db:"body_appendix"`
	CommitSha     string         `db:"commit_sha"`
	ContentSha    string         `db:"content_sha"`
	BaseCommitSha sql.NullString `db:"base_commit_sha"`
	RawText       string         `db:"raw_text"`
}

func (q *Queries) CreatePatch(ctx context.Context, arg CreatePatchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPatch,
		arg.UserID,
		arg.PatchsetID,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorDate,
		arg.Title,
		arg.Body,
		arg.BodyAppendix,
		arg.CommitSha,
		arg.ContentSha,
		arg.BaseCommitSha,
		arg.RawText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPatchRequest = `-- name: CreatePatchRequest :one
INSERT INTO patch_requests (user_id, repo_id, name, text, status, updated_at) VALUES (?, ?, ?, ?, ?, ?) RETURNING id
`

type CreatePatchRequestParams struct {
	UserID    int64     `db:"user_id"`
	RepoID    int64     `db:"repo_id"`
	Name      string    `db:"name"`
	Text      string    `db:"text"`
	Status    Status    `db:"status"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) CreatePatchRequest(ctx context.Context, arg CreatePatchRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPatchRequest,
		arg.UserID,
		arg.RepoID,
		arg.Name,
		arg.Text,
		arg.Status,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPatchset = `-- name: CreatePatchset :one
INSERT INTO patchsets (user_id, patch_request_id, review) VALUES (?, ?, ?) RETURNING id
`

type CreatePatchsetParams struct {
	UserID         int64 `db:"user_id"`
	PatchRequestID int64 `db:"patch_request_id"`
	Review         bool  `db:"review"`
}

func (q *Queries) CreatePatchset(ctx context.Context, arg CreatePatchsetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPatchset, arg.UserID, arg.PatchRequestID, arg.Review)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (user_id, name) VALUES (?, ?) RETURNING id
`

type CreateRepoParams struct {
	UserID int64  `db:"user_id"`
	Name   string `db:"name"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createRepo, arg.UserID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO app_users (pubkey, name) VALUES (?, ?) RETURNING id
`

type CreateUserParams struct {
	Pubkey string `db:"pubkey"`
	Name   string `db:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Pubkey, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePatchsetByID = `-- name: DeletePatchsetByID :exec
DELETE FROM patchsets WHERE id = ?
`

func (q *Queries) DeletePatchsetByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePatchsetByID, id)
	return err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos WHERE user_id = ? AND name = ?
`

type DeleteRepoParams struct {
	UserID int64  `db:"user_id"`
	Name   string `db:"name"`
}

func (q *Queries) DeleteRepo(ctx context.Context, arg DeleteRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteRepo, arg.UserID, arg.Name)
	return err
}

const getAclBanned = `-- name: GetAclBanned :many
SELECT id, pubkey, ip_address, permission, created_at FROM acl WHERE permission = 'banned' AND (pubkey = ? OR ip_address = ?)
`

type GetAclBannedParams struct {
	Pubkey    sql.NullString `db:"pubkey"`
	IpAddress sql.NullString `db:"ip_address"`
}

func (q *Queries) GetAclBanned(ctx context.Context, arg GetAclBannedParams) ([]Acl, error) {
	rows, err := q.db.QueryContext(ctx, getAclBanned, arg.Pubkey, arg.IpAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Acl
	for rows.Next() {
		var i Acl
		if err := rows.Scan(
			&i.ID,
			&i.Pubkey,
			&i.IpAddress,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventLogs = `-- name: GetEventLogs :many
SELECT id, user_id, repo_id, patch_request_id, patchset_id, event, data, created_at FROM event_logs ORDER BY created_at DESC
`

func (q *Queries) GetEventLogs(ctx context.Context) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, getEventLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventLog
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoID,
			&i.PatchRequestID,
			&i.PatchsetID,
			&i.Event,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventLogsByPrID = `-- name: GetEventLogsByPrID :many
SELECT id, user_id, repo_id, patch_request_id, patchset_id, event, data, created_at FROM event_logs WHERE patch_request_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetEventLogsByPrID(ctx context.Context, patchRequestID sql.NullInt64) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, getEventLogsByPrID, patchRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventLog
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoID,
			&i.PatchRequestID,
			&i.PatchsetID,
			&i.Event,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventLogsByRepoID = `-- name: GetEventLogsByRepoID :many
SELECT id, user_id, repo_id, patch_request_id, patchset_id, event, data, created_at FROM event_logs WHERE repo_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetEventLogsByRepoID(ctx context.Context, repoID sql.NullInt64) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, getEventLogsByRepoID, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventLog
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoID,
			&i.PatchRequestID,
			&i.PatchsetID,
			&i.Event,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventLogsByUserID = `-- name: GetEventLogsByUserID :many
SELECT id, user_id, repo_id, patch_request_id, patchset_id, event, data, created_at FROM event_logs
WHERE event_logs.user_id = ?1
    OR event_logs.patch_request_id IN (
        SELECT id FROM patch_requests WHERE patch_requests.user_id = ?1
    )
ORDER BY created_at DESC
`

func (q *Queries) GetEventLogsByUserID(ctx context.Context, userID int64) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, getEventLogsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventLog
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoID,
			&i.PatchRequestID,
			&i.PatchsetID,
			&i.Event,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPatchRequestByID = `-- name: GetPatchRequestByID :one
SELECT id, user_id, repo_id, name, text, status, created_at, updated_at FROM patch_requests WHERE id = ? ORDER BY created_at DESC
`

func (q *Queries) GetPatchRequestByID(ctx context.Context, id int64) (PatchRequest, error) {
	row := q.db.QueryRowContext(ctx, getPatchRequestByID, id)
	var i PatchRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.Name,
		&i.Text,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatchRequestRepoID = `-- name: GetPatchRequestRepoID :one
SELECT repo_id FROM patch_requests WHERE id = ?
`

func (q *Queries) GetPatchRequestRepoID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPatchRequestRepoID, id)
	var repo_id int64
	err := row.Scan(&repo_id)
	return repo_id, err
}

const getPatchRequests = `-- name: GetPatchRequests :many
SELECT id, user_id, repo_id, name, text, status, created_at, updated_at FROM patch_requests ORDER BY id DESC
`

func (q *Queries) GetPatchRequests(ctx context.Context) ([]PatchRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPatchRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatchRequest
	for rows.Next() {
		var i PatchRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoID,
			&i.Name,
			&i.Text,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPatchRequestsByPubkey = `-- name: GetPatchRequestsByPubkey :many
SELECT pr.id, pr.user_id, pr.repo_id, pr.name, pr.text, pr.status, pr.created_at, pr.updated_at FROM patch_requests pr, app_users au WHERE pr.user_id = au.id AND au.pubkey = ? ORDER BY pr.id DESC
`

func (q *Queries) GetPatchRequestsByPubkey(ctx context.Context, pubkey string) ([]PatchRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPatchRequestsByPubkey, pubkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatchRequest
	for rows.Next() {
		var i PatchRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoID,
			&i.Name,
			&i.Text,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPatchRequestsByRepoID = `-- name: GetPatchRequestsByRepoID :many
SELECT id, user_id, repo_id, name, text, status, created_at, updated_at FROM patch_requests WHERE repo_id = ? ORDER BY id DESC
`

func (q *Queries) GetPatchRequestsByRepoID(ctx context.Context, repoID int64) ([]PatchRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPatchRequestsByRepoID, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatchRequest
	for rows.Next() {
		var i PatchRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoID,
			&i.Name,
			&i.Text,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPatchesByPatchsetID = `-- name: GetPatchesByPatchsetID :many
SELECT id, user_id, patchset_id, author_name, author_email, author_date, title, body, body_appendix, commit_sha, content_sha, raw_text, base_commit_sha, created_at FROM patches WHERE patchset_id = ? ORDER BY created_at ASC, id ASC
`

func (q *Queries) GetPatchesByPatchsetID(ctx context.Context, patchsetID int64) ([]Patch, error) {
	rows, err := q.db.QueryContext(ctx, getPatchesByPatchsetID, patchsetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patch
	for rows.Next() {
		var i Patch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PatchsetID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorDate,
			&i.Title,
			&i.Body,
			&i.BodyAppendix,
			&i.CommitSha,
			&i.ContentSha,
			&i.RawText,
			&i.BaseCommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPatchsetByID = `-- name: GetPatchsetByID :one
SELECT id, user_id, patch_request_id, review, created_at FROM patchsets WHERE id = ?
`

func (q *Queries) GetPatchsetByID(ctx context.Context, id int64) (Patchset, error) {
	row := q.db.QueryRowContext(ctx, getPatchsetByID, id)
	var i Patchset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PatchRequestID,
		&i.Review,
		&i.CreatedAt,
	)
	return i, err
}

const getPatchsetsByPrID = `-- name: GetPatchsetsByPrID :many
SELECT id, user_id, patch_request_id, review, created_at FROM patchsets WHERE patch_request_id = ? ORDER BY created_at ASC
`

func (q *Queries) GetPatchsetsByPrID(ctx context.Context, patchRequestID int64) ([]Patchset, error) {
	rows, err := q.db.QueryContext(ctx, getPatchsetsByPrID, patchRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patchset
	for rows.Next() {
		var i Patchset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PatchRequestID,
			&i.Review,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, user_id, name, created_at, updated_at FROM repos WHERE id = ?
`

func (q *Queries) GetRepoByID(ctx context.Context, id int64) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepoByID, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByName = `-- name: GetRepoByName :one
SELECT id, user_id, name, created_at, updated_at FROM repos WHERE name = ?
`

func (q *Queries) GetRepoByName(ctx context.Context, name string) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepoByName, name)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByNameAndUser = `-- name: GetRepoByNameAndUser :one
SELECT id, user_id, name, created_at, updated_at FROM repos WHERE user_id = ? AND name = ?
`

type GetRepoByNameAndUserParams struct {
	UserID int64  `db:"user_id"`
	Name   string `db:"name"`
}

func (q *Queries) GetRepoByNameAndUser(ctx context.Context, arg GetRepoByNameAndUserParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepoByNameAndUser, arg.UserID, arg.Name)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepos = `-- name: GetRepos :many
SELECT id, user_id, name, created_at, updated_at FROM repos
`

func (q *Queries) GetRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, getRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, pubkey, name, created_at, updated_at FROM app_users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, pubkey, name, created_at, updated_at FROM app_users WHERE name = ?
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPubkey = `-- name: GetUserByPubkey :one
SELECT id, pubkey, name, created_at, updated_at FROM app_users WHERE pubkey = ?
`

func (q *Queries) GetUserByPubkey(ctx context.Context, pubkey string) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByPubkey, pubkey)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, pubkey, name, created_at, updated_at FROM app_users
`

func (q *Queries) GetUsers(ctx context.Context) ([]AppUser, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppUser
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.Pubkey,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatchRequestName = `-- name: UpdatePatchRequestName :exec
UPDATE patch_requests SET name = ? WHERE id = ?
`

type UpdatePatchRequestNameParams struct {
	Name string `db:"name"`
	ID   int64  `db:"id"`
}

func (q *Queries) UpdatePatchRequestName(ctx context.Context, arg UpdatePatchRequestNameParams) error {
	_, err := q.db.ExecContext(ctx, updatePatchRequestName, arg.Name, arg.ID)
	return err
}

const updatePatchRequestStatus = `-- name: UpdatePatchRequestStatus :exec
UPDATE patch_requests SET status = ? WHERE id = ?
`

type UpdatePatchRequestStatusParams struct {
	Status Status `db:"status"`
	ID     int64  `db:"id"`
}

func (q *Queries) UpdatePatchRequestStatus(ctx context.Context, arg UpdatePatchRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePatchRequestStatus, arg.Status, arg.ID)
	return err
}
